version: "3"
services:
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=racky
      - MONGO_PASSWORD=password
    command: sh -c "npm install -g nodemon && npm install && npm run dev"
  
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=racky
      - MONGO_INITDB_ROOT_PASSWORD=password
